---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carina-deployment
  labels:
    app: carina
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carina
  template:
    metadata:
      labels:
        app: carina
    spec:
      containers:
      - name: carina
        image: rmarra/tcc-carioca:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: carina-service
spec:
  selector:
    app: carina
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: 8000
