
name: Test & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t ${DOCKER_USERNAME}/tcc-carioca:latest -f ./Dockerfile .

      - name: Run Test
        run: docker run ${DOCKER_USERNAME}/tcc-carioca:latest pytest

      - name: Deploy Image
        run: docker push ${DOCKER_USERNAME}/tcc-carioca:latest

